# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "debug"
client_id = "427d4d91b25c5a722f933e3560e3bd3c"
application_url = "https://sega-gains-managers-cialis.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sega-gains-managers-cialis.trycloudflare.com/auth/callback",
  "https://sega-gains-managers-cialis.trycloudflare.com/auth/shopify/callback",
  "https://sega-gains-managers-cialis.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e581e694.myshopify.com"
